//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Water_Quality_And_Flood_Control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationData
    {
        public string AreaName { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
    }
}
